---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  creationTimestamp: null
  name: externalsecrets-template-test-dest
spec:
  refreshInterval: 30s
  secretStoreRef:
    kind: SecretStore
    name: externalsecrets-template-test-source
  target:
    name: externalsecrets-template-test-dest # name of the k8s Secret to be created
    template:
      type: kubernetes.io/tls
      data:
        tls.crt: '{{ $certs := index . "tls.crt" | filterPEM "CERTIFICATE" | splitList "-----END CERTIFICATE-----\n"}}{{ range $index, $element := $certs}}{{- if (eq (int $index) 0)}}{{if $element}}{{$element}}{{"-----END CERTIFICATE-----\n"}}{{end}}{{end}}{{end}}'
        tls.key: '{{ index . "tls.key" }}'
        ca.crt: '{{ $certs := index . "tls.crt" | filterPEM "CERTIFICATE" | splitList "-----END CERTIFICATE-----\n"}}{{ range $index, $element := $certs}}{{- if (ge (int $index) 1)}}{{if $element}}{{$element}}{{"-----END CERTIFICATE-----\n"}}{{end}}{{end}}{{end}}'
  data:
    - secretKey: tls.crt
      remoteRef:
        key: externalsecrets-template-test-source
        property: tls.crt
    - secretKey: tls.key
      remoteRef:
        key: externalsecrets-template-test-source
        property: tls.key
