---
apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  creationTimestamp: null
  name: externalsecrets-template-test-source
spec:
  provider:
    kubernetes:
      # with this, the store is able to pull only from `openshift-ingress` namespace
      remoteNamespace: externalsecrets-template-test-source
      server:
        url: "https://kubernetes.default.svc" # url is optional. If omitted, defaults to kubernetes.default. If using external kube api, consider auth methods including token and generate serviceaccount token at target cluster instead.
        caProvider:
          type: ConfigMap
          name: kube-root-ca.crt
          key: ca.crt
      auth:
        serviceAccount:
          name: externalsecrets-template-test-dest
