apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: externalsecrets-template-test-dest
resources:
- resources/namespace.yaml
- resources/secretstore.yaml
- resources/serviceaccount.yaml
- resources/externalsecret.yaml
