apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: externalsecrets-template-test-source
spec:
  dnsNames:
    - simple-test-source.apps.example.com
  issuerRef:
    group: cert-manager.io
    kind: ClusterIssuer
    name: dk8se-letsencrypt
  secretName: externalsecrets-template-test-source
  usages:
    - digital signature
    - key encipherment
